class HelpContent {
  static const List<Map<String, dynamic>> pages = [
    {
      'title': 'Projekt-Dashboard Übersicht',
      'content': [
        'Das Projekt-Dashboard ist die zentrale Anlaufstelle für die Verwaltung deines Projekts. Es besteht aus drei Hauptbereichen:',
        'Navigation:',
        '• Übersicht: Zeigt Projekt-Notizen, Assessment, Wissensbasis und Fortschritt',
        '• Dateien: Verwalte und lade PDF-Dokumente hoch',
        '• Chatbot Test: Teste den KI-Assistenten mit deinen Dokumenten',
        'Dashboard-Komponenten:',
        '• Projekt-Notizen: Gib wichtige Kontextinformationen für den Chatbot ein',
        '• Vollständigkeits-Indikator: Zeigt die Qualität deiner Dokumentenbasis',
        '• Projekt-Assessment: Automatische Bewertung der hochgeladenen Dokumente',
        '• Wissensbasis: Übersicht über extrahierte Informationen aus deinen Dokumenten',
        'Wichtig: Die Projekt-Notizen sind essentiell für eine korrekte Vollständigkeits-Bewertung! Ohne diese Angaben kann das System nicht einschätzen, welche Dokumente für dein spezifisches Projekt relevant sind.',
      ],
    },
    {
      'title': 'Dokumente verwalten',
      'content': [
        'Im "Dateien"-Tab kannst du PDF-Dokumente hochladen und verwalten:',
        'Unterstützte Dateiformate:',
        '• Nur PDF-Dateien werden aktuell unterstützt',
        '• Die Inhalte müssen als Text vorliegen (keine reinen Scans)',
        '• Empfohlene Dokumente: Modulhandbücher, Studienverlaufspläne, Prüfungsordnungen',
        'Upload-Prozess:',
        '• Klicke auf "Datei auswählen" und wähle deine PDF-Datei',
        '• Gib eine kurze Beschreibung des Dokuments ein',
        '• Bestätige mit "Hochladen"',
        '• Verfolge den Verarbeitungsfortschritt in Echtzeit',
        'Verwaltung:',
        '• Hochgeladene Dateien werden automatisch verarbeitet und analysiert',
        '• Du kannst jederzeit Dateien löschen oder weitere hinzufügen',
        '• Je mehr relevante Dokumente, desto besser die Chatbot-Antworten',
      ],
    },
    {
      'title': 'KI-Assessment & Wissensbasis',
      'content': [
        'Das System erstellt automatisch eine Bewertung deines Projekts:',
        'Vollständigkeits-Indikator:',
        '• Zeigt die Qualität deiner Dokumentenbasis in Prozent',
        '• ACHTUNG: Basiert auf den Projekt-Notizen - diese müssen ausgefüllt sein!',
        '• Grün (80-100%): Sehr gute Grundlage für den Chatbot',
        '• Orange (60-79%): Solide Basis, weitere Dokumente empfohlen',
        '• Rot (unter 60%): Mehr Dokumente für bessere Ergebnisse nötig',
        'Projekt-Assessment:',
        '• Automatische Analyse der hochgeladenen Dokumente',
        '• Zeigt vorhandene und fehlende Dokumenttypen',
        '• Gibt Tipps für Verbesserungen',
        '• Aktualisiert sich automatisch bei neuen Uploads',
        'Wissensbasis:',
        '• Überblick über extrahierte Informationen',
        '• Zeigt den aktuellen Wissensstand des Chatbots',
        '• "Chatbot testen"-Button für direkten Zugriff auf den KI-Assistenten',
      ],
    },
    {
      'title': 'Chatbot optimal nutzen',
      'content': [
        'Der Chatbot im "Chatbot Test"-Tab kann alle Fragen zu deinen Dokumenten beantworten:',
        'Beste Ergebnisse erzielen:',
        '• ZUERST: Fülle die Projekt-Notizen aus - diese sind fundamental wichtig!',
        '• Ohne Projekt-Notizen kann der Vollständigkeits-Indikator nicht funktionieren',
        '• Lade alle relevanten Dokumente hoch (Modulhandbücher, Prüfungsordnungen, etc.)',
        '• Warte, bis der Vollständigkeits-Indikator mindestens 60% zeigt',
        'Beispiel-Fragen:',
        '• "Wann ist die Anmeldefrist für das Modul XY?"',
        '• "Wie viele ECTS bekomme ich für XY?"',
        '• "Welche Voraussetzungen brauche ich für XY?"',
        '• "Welche Module sind für eine Spezialisierung in Y relevant?"',
        'Erweiterte Funktionen:',
        '• Der Chatbot kann kontextbezogene Empfehlungen geben',
        '• Komplexe, verknüpfte Fragen werden verstanden',
        '• Antworten basieren ausschließlich auf deinen hochgeladenen Dokumenten',
        'Hinweis: Bei niedrigem Vollständigkeits-Indikator können die Antworten unvollständig sein.',
      ],
    },
  ];
}