class ProjectHelpContent {
  static const List<Map<String, dynamic>> pages = [
    {
      'title': 'Was ist ein Projekt?',
      'content': [
        'Ein Projekt ist wie ein intelligenter Ordner für deine Dokumente. Jedes Projekt steht für einen bestimmten Kontext, z.B. einen Studiengang, ein Fach oder ein Thema.',
        'Vorteile von Projekten:',
        '• Organisation: Halte Dokumente für verschiedene Studiengänge oder Themen getrennt',
        '• Kontext: Der Chatbot beantwortet Fragen immer nur im Kontext des ausgewählten Projekts',
        '• Effizienz: Du musst nicht immer wieder alle Dokumente hochladen, sondern wechselst einfach das Projekt',
        '• Intelligente Bewertung: Jedes Projekt erhält automatisch eine Vollständigkeitsbewertung',
        'Projekt-Features:',
        '• Dashboard mit Übersicht über alle wichtigen Informationen',
        '• Automatisches Assessment der Dokumentenqualität',
        '• Wissensbasis mit extrahierten Informationen',
        '• Integrierter Chatbot für projektspezifische Fragen',
      ],
    },
    {
      'title': 'Projekte erstellen und verwalten',
      'content': [
        'Neues Projekt erstellen:',
        '• Klicke auf das Plus-Symbol (+) in der oberen rechten Ecke',
        '• Es empfiehlt sich, ein Projekt pro Studiengang/Fakultät zu erstellen',
        '• Gib einen aussagekräftigen Namen ein, z.B. "Master Wirtschaftsinformatik"',
        '• Füge eine kurze Beschreibung hinzu, die dem Chatbot den Kontext erklärt, dies kannst du später noch bearbeiten',
        'Projekte verwalten:',
        '• Klicke auf ein Projekt in der Liste, um das Dashboard zu öffnen',
        '• Verwende das Mülleimer-Symbol zum Löschen von Projekten',
        ''
        'Dashboard-Navigation:',
        '• Übersicht: Zentrale Anlaufstelle mit allen wichtigen Informationen',
        '• Dateien: Dokumenten-Upload und -Verwaltung',
        '• Chatbot Test: Direkter Zugriff auf den KI-Assistenten',
      ],
    },
    {
      'title': 'Projekt-Dashboard optimal nutzen',
      'content': [
        'Das Dashboard ist das Herzstück deines Projekts. So nutzt du es optimal:',
        'Projekt-Notizen:',
        '• Fülle die Notizen mit wichtigen Kontextinformationen aus',
        '• Beschreibe den Studiengang, wichtige Ziele oder Besonderheiten',
        '• Diese Informationen helfen dem Chatbot, bessere Antworten zu geben',
        'Vollständigkeits-Indikator beachten:',
        '• Zeigt dir, wie gut deine Dokumentenbasis ist',
        '• Grün (80-100%): Optimale Grundlage für den Chatbot',
        '• Orange (60-79%): Gute Basis, weitere Dokumente empfohlen',
        '• Rot (unter 60%): Mehr Dokumente für bessere Ergebnisse nötig',
        'Assessment und Wissensbasis:',
        '• Werden automatisch aktualisiert, wenn neue Dokumente hochgeladen werden',
        '• Zeigen dir, welche Informationen bereits verfügbar sind',
        '• Geben Tipps für Verbesserungen',
        '• Nutze den "Chatbot testen"-Button, um deinen Chatbot zu testen',
      ],
    },
    {
      'title': 'Tipps für erfolgreiche Projekte',
      'content': [
        'Klare Projektnamen und Beschreibungen:',
        '• Verwende Namen, die den Inhalt klar beschreiben, z.B. "Bachelor BWL PO 2023"',
        '• Füge in die Projekt-Notizen wichtige Kontextinformationen hinzu',
        '• Das hilft dem Chatbot, präzisere Antworten zu geben',
        'Strukturierte Dokumentensammlung:',
        '• Lade die wichtigsten Dokumente zuerst hoch (Modulhandbuch, Prüfungsordnung)',
        '• Mische nicht zu viele unterschiedliche Themen in einem Projekt',
        '• Erstelle für verschiedene Studiengänge separate Projekte',
        'Qualitätskontrolle:',
        '• Achte auf den Vollständigkeits-Indikator im Dashboard',
        '• Lies das automatische Assessment, um fehlende Dokumente zu identifizieren',
        '• Teste den Chatbot regelmäßig mit typischen Fragen',
        'Wartung und Aktualisierung:',
        '• Halte deine Dokumente aktuell',
        '• Entferne veraltete Dateien',
        '• Nutze die Aktualisierungs-Buttons für Assessment und Wissensbasis',
      ],
    },
  ];
}